backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

site_url: https://creativegenerationnyc.netlify.app

collections:
  - name: "art"
    label: "Art"
    folder: "content/art"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", default: "" }

  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime", default: "" }

  - name: "books"
    label: "Books"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Book File (PDF)", name: "file", widget: "file", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "" }
